name: Flutter Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Крок 1: Встановлюємо Java, яка потрібна для збірки Android
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'zulu'

    # Крок 2: Встановлюємо Flutter SDK (найновішу стабільну версію)
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    # Крок 3: Завантажуємо залежності проєкту (бібліотеки)
    - name: Install dependencies
      run: flutter pub get

    # Крок 4: Запускаємо збірку APK у режимі релізу
    - name: Build APK
      run: flutter build apk --release --no-tree-shake-icons

    # Крок 5: Зберігаємо готовий APK у вкладку Artifacts
    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: SketchIDE-release-apk
        path: build/app/outputs/flutter-apk/app-release.apk
